name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Frontend Image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/menn-frontend
        docker buildx build --platform linux/amd64 -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} ./frontend --push

    - name: Build and Push Backend Image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/menn-backend
        docker buildx build --platform linux/amd64 -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} ./backend --push

    - name: Trigger update in menn-k8s repo
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.K8S_REPO_TOKEN }}
        repository: hsb943/menn-k8s
        event-type: update-manifests
        client-payload: '{"sha": "${{ github.sha }}"}'







